import pygame
import math
import random

pygame.init()
WIDTH, HEIGHT = 800, 500
win = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Hangman Game!")

RADIUS = 20
GAP = 15
letters = []
startx = round((WIDTH - (RADIUS * 2 + GAP) * 13) / 2)
starty = 400
A = 65
for i in range(26):
    x = startx + GAP * 2 + ((RADIUS * 2 + GAP) * (i % 13))
    y = starty + ((i // 13) * (GAP + RADIUS * 2))
    letters.append([x, y, chr(A + i), True])
    
LETTER_FONT = pygame.font.SysFont('comicsans', 40)
WORD_FONT = pygame.font.SysFont('comicsans', 60)
TITLE_FONT = pygame.font.SysFont('comicsans', 70)

images = []
for i in range(7):
    image = pygame.image.load("hangman" + str(i) + ".png")
    images.append(image)

hangman_status = 0
words = ['PEOPLE','HISTORY''WAY','ART','WORLD','INFORMATION','MAP','TWO','FAMILY','GOVERNMENT','HEALTH','SYSTEM','COMPUTER','MEAT','YEAR','THANKS','MUSIC','PERSON','READING','METHOD','DATA','FOOD','UNDERSTANDING','THEORY','LAW','BIRD','LITERATURE','PROBLEM','SOFTWARE','CONTROL','KNOWLEDGE','POWER','ABILITY','ECONOMICS','LOVE','INTERNET','TELEVISION','SCIENCE','LIBRARY','NATURE','FACT','PRODUCT','IDEA','TEMPERATURE','INVESTMENT','AREA','SOCIETY','ACTIVITY','STORY','INDUSTRY','MEDIA','THING','OVEN','COMMUNITY','DEFINITION','SAFETY','QUALITY','DEVELOPMENT','LANGUAGE','MANAGEMENT','PLAYER','VARIETY','VIDEO','WEEK','SECURITY','COUNTRY','EXAM','MOVIE','ORGANIZATION','EQUIPMENT','PHYSICS','ANALYSIS','POLICY','SERIES','THOUGHT','BASIS','BOYFRIEND','DIRECTION','STRATEGY','TECHNOLOGY','ARMY','CAMERA','FREEDOM','PAPER','ENVIRONMENT','CHILD','INSTANCE','MONTH','TRUTH','MARKETING','UNIVERSITY','WRITING','ARTICLE','DEPARTMENT','DIFFERENCE','GOAL','NEWS','AUDIENCE','FISHING','GROWTH','INCOME','MARRIAGE','USER','COMBINATION','FAILURE','MEANING','MEDICINE','PHILOSOPHY','TEACHER','COMMUNICATION','NIGHT','CHEMISTRY','DISEASE','DISK','ENERGY','NATION','ROAD','ROLE','SOUP','ADVERTISING','LOCATION','SUCCESS','ADDITION','APARTMENT','EDUCATION','MATH','MOMENT','PAINTING','POLITICS','ATTENTION','DECISION','EVENT','PROPERTY','SHOPPING','STUDENT','WOOD','COMPETITION','DISTRIBUTION','ENTERTAINMENT','OFFICE','POPULATION','PRESIDENT','UNIT','CATEGORY','CIGARETTE','CONTEXT','INTRODUCTION','OPPORTUNITY','PERFORMANCE','DRIVER','FLIGHT','LENGTH','MAGAZINE','NEWSPAPER','RELATIONSHIP','TEACHING','CELL','DEALER','DEBATE','FINDING','LAKE','MEMBER','MESSAGE','PHONE','SCENE','APPEARANCE','ASSOCIATION','CONCEPT','CUSTOMER','DEATH','DISCUSSION','HOUSING','INFLATION','INSURANCE','MOOD','WOMAN','ADVICE','BLOOD','EFFORT','EXPRESSION','IMPORTANCE','OPINION','PAYMENT','REALITY','RESPONSIBILITY','SITUATION','SKILL','STATEMENT','WEALTH','APPLICATION','CITY','DEPTH','ESTATE','FOUNDATION','GRANDMOTHER','HEART','PERSPECTIVE','PHOTO','RECIPE','STUDIO','TOPIC','COLLECTION','DEPRESSION','IMAGINATION','PASSION','PERCENTAGE','RESOURCE','SETTING','AD','AGENCY','COLLEGE','CONNECTION','CRITICISM','DEBT','DESCRIPTION','MEMORY','PATIENCE','SECRETARY','SOLUTION','ADMINISTRATION','ASPECT','ATTITUDE','DIRECTOR','PERSONALITY','PSYCHOLOGY','RECOMMENDATION','RESPONSE','SELECTION','STORAGE','VERSION','ALCOHOL','ARGUMENT','COMPLAINT','CONTRACT','EMPHASIS','HIGHWAY','LOSS','MEMBERSHIP', 'POSSESSION' 'PREPARATION' 'STEAK' 'UNION' 'AGREEMENT' 'CANCER' 'CURRENCY' 'EMPLOYMENT' 'ENGINEERING' 'ENTRY' 'INTERACTION' 'LIMIT' 'MIXTURE' 'PREFERENCE' 'REGION' 'REPUBLIC' 'SEAT' 'TRADITION' 'VIRUS' 'ACTOR' 'CLASSROOM' 'DELIVERY' 'DEVICE' 'DIFFICULTY' 'DRAMA' 'ELECTION' 'ENGINE' 'FOOTBALL' 'GUIDANCE' 'HOTEL' 'MATCH' 'OWNER' 'PRIORITY' 'PROTECTION' 'SUGGESTION' 'TENSION' 'VARIATION' 'ANXIETY' 'ATMOSPHERE' 'AWARENESS' 'BREAD' 'CLIMATE' 'COMPARISON' 'CONFUSION' 'CONSTRUCTION' 'ELEVATOR' 'EMOTION' 'EMPLOYEE' 'EMPLOYER' 'GUEST' 'HEIGHT' 'LEADERSHIP' 'MALL' 'MANAGER' 'OPERATION' 'RECORDING' 'RESPECT' 'SAMPLE' 'TRANSPORTATION' 'BORING' 'CHARITY' 'COUSIN' 'DISASTER' 'EDITOR' 'EFFICIENCY' 'EXCITEMENT' 'EXTENT' 'FEEDBACK' 'GUITAR' 'HOMEWORK' 'LEADER' 'MOM' 'OUTCOME' 'PERMISSION' 'PRESENTATION' 'PROMOTION' 'REFLECTION' 'REFRIGERATOR' 'RESOLUTION' 'REVENUE' 'SESSION' 'SINGER' 'TENNIS' 'BASKET' 'BONUS' 'CABINET' 'CHILDHOOD' 'CHURCH' 'CLOTHES' 'COFFEE' 'DINNER' 'DRAWING' 'HAIR' 'HEARING' 'INITIATIVE' 'JUDGMENT' 'LAB' 'MEASUREMENT' 'MODE' 'MUD' 'ORANGE' 'POETRY' 'POLICE' 'POSSIBILITY' 'PROCEDURE' 'QUEEN' 'RATIO' 'RELATION' 'RESTAURANT' 'SATISFACTION' 'SECTOR' 'SIGNATURE' 'SIGNIFICANCE' 'SONG' 'TOOTH' 'TOWN' 'VEHICLE' 'VOLUME' 'WIFE' 'ACCIDENT' 'AIRPORT' 'APPOINTMENT' 'ARRIVAL' 'ASSUMPTION' 'BASEBALL' 'CHAPTER' 'COMMITTEE' 'CONVERSATION' 'DATABASE' 'ENTHUSIASM' 'ERROR' 'EXPLANATION' 'FARMER' 'GATE' 'GIRL' 'HALL' 'HISTORIAN' 'HOSPITAL' 'INJURY' 'INSTRUCTION' 'MAINTENANCE' 'MANUFACTURER' 'MEAL' 'PERCEPTION' 'PIE' 'POEM' 'PRESENCE' 'PROPOSAL' 'RECEPTION' 'REPLACEMENT' 'REVOLUTION' 'RIVER' 'SON' 'SPEECH' 'TEA' 'VILLAGE' 'WARNING' 'WINNER' 'WORKER' 'WRITER' 'ASSISTANCE' 'BREATH' 'BUYER' 'CHEST' 'CHOCOLATE' 'CONCLUSION' 'CONTRIBUTION' 'COOKIE' 'COURAGE' 'DAD' 'DESK' 'DRAWER' 'ESTABLISHMENT' 'EXAMINATION' 'GARBAGE' 'GROCERY' 'HONEY' 'IMPRESSION' 'IMPROVEMENT' 'INDEPENDENCE' 'INSECT' 'INSPECTION' 'INSPECTOR' 'KING' 'LADDER' 'MENU' 'PENALTY' 'PIANO' 'POTATO' 'PROFESSION' 'PROFESSOR' 'QUANTITY' 'REACTION' 'REQUIREMENT' 'SALAD' 'SISTER' 'SUPERMARKET' 'TONGUE' 'WEAKNESS' 'WEDDING' 'AFFAIR' 'AMBITION' 'ANALYST' 'APPLE' 'ASSIGNMENT' 'ASSISTANT' 'BATHROOM' 'BEDROOM' 'BEER' 'BIRTHDAY' 'CELEBRATION' 'CHAMPIONSHIP' 'CHEEK' 'CLIENT' 'CONSEQUENCE' 'DEPARTURE' 'DIAMOND' 'DIRT' 'EAR' 'FORTUNE' 'FRIENDSHIP' 'FUNERAL' 'GENE' 'GIRLFRIEND' 'HAT' 'INDICATION' 'INTENTION' 'LADY' 'MIDNIGHT' 'NEGOTIATION' 'OBLIGATION' 'PASSENGER' 'PIZZA' 'PLATFORM' 'POET' 'POLLUTION' 'RECOGNITION' 'REPUTATION' 'SHIRT' 'SIR' 'SPEAKER' 'STRANGER' 'SURGERY' 'SYMPATHY' 'TALE' 'THROAT' 'TRAINER' 'UNCLE' 'YOUTH' 'TIME' 'WORK' 'FILM' 'WATER' 'MONEY' 'EXAMPLE' 'WHILE' 'BUSINESS' 'STUDY' 'GAME' 'LIFE' 'FORM' 'AIR' 'DAY' 'PLACE' 'NUMBER' 'PART' 'FIELD' 'FISH' 'BACK' 'PROCESS' 'HEAT' 'HAND' 'EXPERIENCE' 'JOB' 'BOOK' 'END' 'POINT' 'TYPE' 'HOME' 'ECONOMY' 'VALUE' 'BODY' 'MARKET' 'GUIDE' 'INTEREST' 'STATE' 'RADIO' 'COURSE' 'COMPANY' 'PRICE' 'SIZE' 'CARD' 'LIST' 'MIND' 'TRADE' 'LINE' 'CARE' 'GROUP' 'RISK' 'WORD' 'FAT' 'FORCE' 'KEY' 'LIGHT' 'TRAINING' 'NAME' 'SCHOOL' 'TOP' 'AMOUNT' 'LEVEL' 'ORDER' 'PRACTICE' 'RESEARCH' 'SENSE' 'SERVICE' 'PIECE' 'WEB' 'BOSS' 'SPORT' 'FUN' 'HOUSE' 'PAGE' 'TERM' 'TEST' 'ANSWER' 'SOUND' 'FOCUS' 'MATTER' 'KIND' 'SOIL' 'BOARD' 'OIL' 'PICTURE' 'ACCESS' 'GARDEN' 'RANGE' 'RATE' 'REASON' 'FUTURE' 'SITE' 'DEMAND' 'EXERCISE' 'IMAGE' 'CASE' 'CAUSE' 'COAST' 'ACTION' 'AGE' 'BAD' 'BOAT' 'RECORD' 'RESULT' 'SECTION' 'BUILDING' 'MOUSE' 'CASH' 'CLASS' 'NOTHING' 'PERIOD' 'PLAN' 'STORE' 'TAX' 'SIDE' 'SUBJECT' 'SPACE' 'RULE' 'STOCK' 'WEATHER' 'CHANCE' 'FIGURE' 'MAN' 'MODEL' 'SOURCE' 'BEGINNING' 'EARTH' 'PROGRAM' 'CHICKEN' 'DESIGN' 'FEATURE' 'HEAD' 'MATERIAL' 'PURPOSE' 'QUESTION' 'ROCK' 'SALT' 'ACT' 'BIRTH' 'CAR' 'DOG' 'OBJECT' 'SCALE' 'SUN' 'NOTE' 'PROFIT' 'RENT' 'SPEED' 'STYLE' 'WAR' 'BANK' 'CRAFT' 'HALF' 'INSIDE' 'OUTSIDE' 'STANDARD' 'BUS' 'EXCHANGE' 'EYE' 'FIRE' 'POSITION' 'PRESSURE' 'STRESS' 'ADVANTAGE' 'BENEFIT' 'BOX' 'FRAME' 'ISSUE' 'STEP' 'CYCLE' 'FACE' 'ITEM' 'METAL' 'PAINT' 'REVIEW' 'ROOM' 'SCREEN' 'STRUCTURE' 'VIEW' 'ACCOUNT' 'BALL' 'DISCIPLINE' 'MEDIUM' 'SHARE' 'BALANCE' 'BIT' 'BLACK' 'BOTTOM' 'CHOICE' 'GIFT' 'IMPACT' 'MACHINE' 'SHAPE' 'TOOL' 'WIND' 'ADDRESS' 'AVERAGE' 'CAREER' 'CULTURE' 'MORNING' 'POT' 'SIGN' 'TABLE' 'TASK' 'CONDITION' 'CONTACT' 'CREDIT' 'EGG' 'HOPE' 'ICE' 'NETWORK' 'NORTH' 'SQUARE' 'ATTEMPT' 'DATE' 'EFFECT' 'LINK' 'POST' 'STAR' 'VOICE' 'CAPITAL' 'CHALLENGE' 'FRIEND' 'SELF' 'SHOT' 'BRUSH' 'COUPLE' 'EXIT' 'FRONT' 'FUNCTION' 'LACK' 'LIVING' 'PLANT' 'PLASTIC' 'SPOT' 'SUMMER' 'TASTE' 'THEME' 'TRACK' 'WING' 'BRAIN' 'BUTTON' 'CLICK' 'DESIRE' 'FOOT' 'GAS' 'INFLUENCE' 'NOTICE' 'RAIN' 'WALL' 'BASE' 'DAMAGE' 'DISTANCE' 'FEELING' 'PAIR' 'SAVINGS' 'STAFF' 'SUGAR' 'TARGET' 'TEXT' 'ANIMAL' 'AUTHOR' 'BUDGET' 'DISCOUNT' 'FILE' 'GROUND' 'LESSON' 'MINUTE' 'OFFICER' 'PHASE' 'REFERENCE' 'REGISTER' 'SKY' 'STAGE' 'STICK' 'TITLE' 'TROUBLE' 'BOWL' 'BRIDGE' 'CAMPAIGN' 'CHARACTER' 'CLUB' 'EDGE' 'EVIDENCE' 'FAN' 'LETTER' 'LOCK' 'MAXIMUM' 'NOVEL' 'OPTION' 'PACK' 'PARK' 'PLENTY' 'QUARTER' 'SKIN' 'SORT' 'WEIGHT' 'BABY' 'BACKGROUND' 'CARRY' 'DISH' 'FACTOR' 'FRUIT' 'GLASS' 'JOINT' 'MASTER' 'MUSCLE' 'RED' 'STRENGTH' 'TRAFFIC' 'TRIP' 'VEGETABLE' 'APPEAL' 'CHART' 'GEAR' 'IDEAL' 'KITCHEN' 'LAND' 'LOG' 'MOTHER' 'NET' 'PARTY' 'PRINCIPLE' 'RELATIVE' 'SALE' 'SEASON' 'SIGNAL' 'SPIRIT' 'STREET' 'TREE' 'WAVE' 'BELT' 'BENCH' 'COMMISSION' 'COPY' 'DROP' 'MINIMUM' 'PATH' 'PROGRESS' 'PROJECT' 'SEA' 'SOUTH' 'STATUS' 'STUFF' 'TICKET' 'TOUR' 'ANGLE' 'BLUE' 'BREAKFAST' 'CONFIDENCE' 'DAUGHTER' 'DEGREE' 'DOCTOR' 'DOT' 'DREAM' 'DUTY' 'ESSAY' 'FATHER' 'FEE' 'FINANCE' 'HOUR' 'JUICE' 'LUCK' 'MILK' 'MOUTH' 'PEACE' 'PIPE' 'STABLE' 'STORM' 'SUBSTANCE' 'TEAM' 'TRICK' 'AFTERNOON' 'BAT' 'BEACH' 'BLANK' 'CATCH' 'CHAIN' 'CONSIDERATION' 'CREAM' 'CREW' 'DETAIL' 'GOLD' 'INTERVIEW' 'KID' 'MARK' 'MISSION' 'PAIN' 'PLEASURE' 'SCORE' 'SCREW' 'SEX' 'SHOP' 'SHOWER' 'SUIT' 'TONE' 'WINDOW' 'AGENT' 'BAND' 'BATH' 'BLOCK' 'BONE' 'CALENDAR' 'CANDIDATE' 'CAP' 'COAT' 'CONTEST' 'CORNER' 'COURT' 'CUP' 'DISTRICT' 'DOOR' 'EAST' 'FINGER' 'GARAGE' 'GUARANTEE' 'HOLE' 'HOOK' 'IMPLEMENT' 'LAYER' 'LECTURE' 'LIE' 'MANNER' 'MEETING' 'NOSE' 'PARKING' 'PARTNER' 'PROFILE' 'RICE' 'ROUTINE' 'SCHEDULE' 'SWIMMING' 'TELEPHONE' 'TIP' 'WINTER' 'AIRLINE' 'BAG' 'BATTLE' 'BED' 'BILL' 'BOTHER' 'CAKE' 'CODE' 'CURVE' 'DESIGNER' 'DIMENSION' 'DRESS' 'EASE' 'EMERGENCY' 'EVENING' 'EXTENSION' 'FARM' 'FIGHT' 'GAP' 'GRADE' 'HOLIDAY' 'HORROR' 'HORSE' 'HOST' 'HUSBAND' 'LOAN' 'MISTAKE' 'MOUNTAIN' 'NAIL' 'NOISE' 'OCCASION' 'PACKAGE' 'PATIENT' 'PAUSE' 'PHRASE' 'PROOF' 'RACE' 'RELIEF' 'SAND' 'SENTENCE' 'SHOULDER' 'SMOKE' 'STOMACH' 'STRING' 'TOURIST' 'TOWEL' 'VACATION' 'WEST' 'WHEEL' 'WINE' 'ARM' 'ASIDE' 'ASSOCIATE' 'BET' 'BLOW' 'BORDER' 'BRANCH' 'BREAST' 'BROTHER' 'BUDDY' 'BUNCH' 'CHIP' 'COACH' 'CROSS' 'DOCUMENT' 'DRAFT' 'DUST' 'EXPERT' 'FLOOR' 'GOD' 'GOLF' 'HABIT' 'IRON' 'JUDGE' 'KNIFE' 'LANDSCAPE' 'LEAGUE' 'MAIL' 'MESS' 'NATIVE' 'OPENING' 'PARENT' 'PATTERN' 'PIN' 'POOL' 'POUND' 'REQUEST' 'SALARY' 'SHAME' 'SHELTER' 'SHOE' 'SILVER' 'TACKLE' 'TANK' 'TRUST' 'ASSIST' 'BAKE' 'BAR' 'BELL' 'BIKE' 'BLAME' 'BOY' 'BRICK' 'CHAIR' 'CLOSET' 'CLUE' 'COLLAR' 'COMMENT' 'CONFERENCE' 'DEVIL' 'DIET' 'FEAR' 'FUEL' 'GLOVE' 'JACKET' 'LUNCH' 'MONITOR' 'MORTGAGE' 'NURSE' 'PACE' 'PANIC' 'PEAK' 'PLANE' 'REWARD' 'ROW' 'SANDWICH' 'SHOCK' 'SPITE' 'SPRAY' 'SURPRISE' 'TILL' 'TRANSITION' 'WEEKEND' 'WELCOME' 'YARD' 'ALARM' 'BEND' 'BICYCLE' 'BITE' 'BLIND' 'BOTTLE' 'CABLE', 'CANDLE', 'CLERK', 'CLOUD', 'CONCERT', 'COUNTER', 'FLOWER', 'GRANDFATHER', 'HARM', 'KNEE', 'LAWYER', 'LEATHER', 'LOAD', 'MIRROR', 'NECK', 'PENSION', 'PLATE', 'PURPLE', 'RUIN', 'SHIP', 'SKIRT', 'SLICE', 'SNOW', 'SPECIALIST', 'STROKE', 'SWITCH', 'TRASH', 'TUNE', 'ZONE', 'ANGER', 'AWARD', 'BID', 'BITTER', 'BOOT', 'BUG', 'CAMP', 'CANDY', 'CARPET', 'CAT', 'CHAMPION', 'CHANNEL', 'CLOCK', 'COMFORT', 'COW', 'CRACK', 'ENGINEER', 'ENTRANCE', 'FAULT', 'GRASS', 'GUY', 'HELL', 'HIGHLIGHT', 'INCIDENT', 'ISLAND', 'JOKE', 'JURY', 'LEG', 'LIP', 'MATE', 'MOTOR' 'NERVE' 'PASSAGE' 'PEN' 'PRIDE' 'PRIEST' 'PRIZE' 'PROMISE' 'RESIDENT' 'RESORT' 'RING' 'ROOF' 'ROPE' 'SAIL' 'SCHEME' 'SCRIPT' 'SOCK' 'STATION' 'TOE' 'TOWER' 'TRUCK' 'WITNESS' 'A' 'YOU' 'IT' 'CAN' 'WILL' 'IF','ONE'
]
word = random.choice(words)
guessed = []

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)


def draw():
    win.fill(WHITE)

    text = TITLE_FONT.render("Hangman Game!", 1, BLACK)
    win.blit(text, (WIDTH / 2 - text.get_width() / 2, 20))

    display_word = ""
    for letter in word:
        if letter in guessed:
            display_word += letter + " "
        else:
            display_word += "_ "
    text = WORD_FONT.render(display_word, 1, BLACK)
    win.blit(text, (400, 200))

    for letter in letters:
        x, y, z visible = letter
        if visible:
            pygame.draw.circle(win, BLACK, (x, y), RADIUS, 3)
            text = LETTER_FONT.render(z,1, BLACK)
            win.blit(text, (x - text.get_width() / 2, y - text.get_height() / 2))

    win.blit(images[hangman_status], (150, 100))
    pygame.display.update()


def display_message(message):
    pygame.time.delay(1000)
    win.fill(WHITE)
    text = WORD_FONT.render(message, 1, BLACK)
    win.blit(text, (WIDTH / 2 - text.get_width() / 2, HEIGHT / 2 - text.get_height() / 2))
    pygame.display.update()
    pygame.time.delay(3000)


def main():
    global hangman_status

    FPS = 60
    clock = pygame.time.Clock()
    run = True

    while run:
        clock.tick(FPS)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                run = False
            if event.type == pygame.MOUSEBUTTONDOWN:
                m_x, m_y = pygame.mouse.get_pos()
                for letter in letters:
                    x, y, z visible = letter
                    if visible:
                        dis = math.sqrt((x - m_x) ** 2 + (y - m_y) ** 2)
                        if dis < RADIUS:
                            letter[3] = False
                            guessed.append(z)
                            if znot in word:
                                hangman_status += 1

        draw()

        won = True
        for letter in word:
            if letter not in guessed:
                won = False
                break

        if won:
            display_message("You WON!")
            break

        if hangman_status == 6:
            display_message("You LOST!")
            break


while True:
    main()
pygame.quit()
